apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: trocketdb
  labels:
    app: trocketdb
    release: c756
spec:
  namespaceSelector:
    matchNames:
    - c756ns
  selector:
    matchLabels:
      app: trocketdb
  endpoints:
  - port: http
    path: /metrics
