apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: trockets2
  labels:
    app: trockets2
    release: c756
spec:
  namespaceSelector:
    matchNames:
    - c756ns
  selector:
    matchLabels:
      app: trockets2
  endpoints:
  - port: http
    path: /metrics
