apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: trockets3
  labels:
    app: trockets3
    release: c756
spec:
  namespaceSelector:
    matchNames:
    - c756ns
  selector:
    matchLabels:
      app: trockets3
  endpoints:
  - port: http
    path: /metrics
