# Set up an integration test of DB, S1, and S2 using a local
# DynamoDB.  Assumes a fresh environment where none of the
# images have been created (or, if an image exists, that it
# is current).  The DynamoDB keeps all tables in memory,
# so no tables exist at startup and any tables created will be
# deleted upon exit.
#
services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -inMemory"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    working_dir: /home/dynamodblocal
  trocketdb:
    build: ../db
    image: ci_db
    container_name: trocketdb
    ports:
      - "30002:30002"
    environment:
      AWS_REGION: 'us-west-2'
      AWS_ACCESS_KEY_ID: 'DUMMY_KEY_ID'
      AWS_SECRET_ACCESS_KEY: 'DUMMY_ACCESS_ KEY'
      SVC_LOADER_TOKEN: 'DUMMY_LOADER_TOKEN'
      DYNAMODB_URL: 'http://dynamodb-local:8000'
  trockets1:
    depends_on:
      - dynamodb-local
      - trocketdb
    build: ../s1
    image: ci_s1
    container_name: trockets1
    ports:
     - "30000:30000"
  trockets2:
    depends_on:
      - dynamodb-local
      - trocketdb
    build: ../s2/v1
    image: ci_s2
    container_name: trockets2
    ports:
     - "30001:30001"
    environment:
      EXER: v1
  test:
    command: "python ci_test.py trockets1 30000 trockets2 30001 nka77"
    depends_on:
      - dynamodb-local
      - trocketdb
      - trockets1
      - trockets2
    build: ./v1
    image: ci_test
    container_name: test
    environment:
      AWS_REGION: 'us-west-2'
      AWS_ACCESS_KEY_ID: 'DUMMY_KEY_ID'
      AWS_SECRET_ACCESS_KEY: 'DUMMY_ACCESS_ KEY'
      SVC_LOADER_TOKEN: 'DUMMY_LOADER_TOKEN'
      DYNAMODB_URL: 'http://dynamodb-local:8000'
